services:
  backend:
          restart: always
          build:
                  context: ../
                  dockerfile: Dockerfile
          container_name: backend-server
          ports:
                  - "8000:8000"
          # command: "uvicorn main:app --host 0.0.0.0 --port 8000"
        #   environment:
                  # - ENVIRONMENT=production
